language: cpp
compiler:
  - g++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - g++-5
      - gcc-5
      - cmake
      - cmake-data
before_install:
  - export CXX="g++-5" CC="gcc-5"
script:
  - cmake --version
  - mkdir build && cd build && cmake .. && cmake --build . && ./moment_test
